name: Lint Python
on:
  pull_request:
  push:
  repository_dispatch:
    types:
      - dispatched_test

env:
  ref: ${{ github.event.client_payload.ref || '' }}

jobs:
  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: >
          python -m pip install
          'pyflakes @ https://github.com/pycqa/pyflakes/tarball/1911c20'
          'pycodestyle @ https://github.com/pycqa/pycodestyle/tarball/d219c68'
          'flake8 @ https://github.com/pycqa/flake8/tarball/3.7.9'
        name: Install Flake8
      - run: "python -m flake8 . --count --select=E9,F7,F82 --show-source"
        name: Flake8 Linting
